HEADER:
  label: "About me"

DOING:
  enabled: false
  label: "🧬 Research Focus"
  items:
    - title: "Cancer Genomics Research"
      icon: "config/assets/icons/cancer.svg"
      description: "Analyzing high-throughput genomic data to understand cancer progression and disease heterogeneity."
    - title: "Single-cell Analysis"
      icon: "config/assets/icons/cell.svg"
      description: "Processing and analyzing single-cell RNA sequencing data to uncover cellular dynamics."
    - title: "Bioinformatics Pipeline Development"
      icon: "config/assets/icons/laptop-code.svg"
      description: "Developing computational tools and pipelines for genomic data analysis."
    - title: "Spatial Transcriptomics"
      icon: "config/assets/icons/colon.svg"
      description: "Analyzing spatial transcriptomic data to understand tissue organization and cell interactions."

CURRENT:
  enabled: true
  label: "📍 Current Position"
  items:
    - title: "PhD Student"
      icon: "config/assets/icons/cshl_logo_alternate-RGB_KO.png"
      description: "Interdisciplinary Quantitative Biology Fellow, University of Colorado Boulder"

TECHNOLOGIES:
  enabled: false
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "Flutter"
      icon: "config/assets/icons/flutter.svg"
    - title: "Git"
      icon: "config/assets/icons/git.svg"
    - title: "Figma"
      icon: "config/assets/icons/figma.svg"
    - title: "Firebase"
      icon: "config/assets/icons/firebase.svg"
    - title: "Pandas"
      icon: "config/assets/icons/pandas.svg"
    - title: "MongoDB"
      icon: "config/assets/icons/mongodb.svg"
    - title: "Dart"
      icon: "config/assets/icons/dart.svg"
    - title: "HTML"
      icon: "config/assets/icons/html.svg"
    - title: "AI"
      icon: "config/assets/icons/ai.svg"
    - title: "Jupyter"
      icon: "config/assets/icons/jupyter.svg"
    - title: "Linux"
      icon: "config/assets/icons/linux.svg"
